package protocol

import (
	"bytes"
	"fmt"
	mapset "github.com/deckarep/golang-set"
	"github.com/idena-network/idena-go/blockchain"
	"github.com/idena-network/idena-go/blockchain/attachments"
	"github.com/idena-network/idena-go/blockchain/types"
	"github.com/idena-network/idena-go/common"
	"github.com/idena-network/idena-go/config"
	"github.com/idena-network/idena-go/core/appstate"
	"github.com/idena-network/idena-go/core/state"
	"github.com/idena-network/idena-go/core/state/snapshot"
	"github.com/idena-network/idena-go/core/upgrade"
	"github.com/idena-network/idena-go/crypto"
	"github.com/idena-network/idena-go/ipfs"
	"github.com/idena-network/idena-go/keystore"
	"github.com/idena-network/idena-go/log"
	"github.com/idena-network/idena-go/stats/collector"
	"github.com/idena-network/idena-go/subscriptions"
	"github.com/idena-network/idena-go/vm/embedded"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/require"
	"github.com/tendermint/tm-db"
	"math/big"
	"testing"
)

const testServingPeer = peer.ID("servingPeer")

// fastSyncTest fast syncs the blocks that source generates after the copy was taken. Its IPFS,
// shared with its chain as on a node, holds no block bodies or receipts until serveTransactions
// adds them.
type fastSyncTest struct {
	source         *blockchain.TestBlockchain
	sourceAppState *appstate.AppState
	fs             *fastSync
	// headers generated by source after the copy, in order.
	headers []*types.Header
	// logs recorded by fs.
	logs []*log.Record
}

func newFastSyncTest(t *testing.T) *fastSyncTest {
	key, err := crypto.GenerateKey()
	require.NoError(t, err)
	addr := crypto.PubkeyToAddress(key.PublicKey)
	consensusCfg := blockchain.GetDefaultConsensusConfig()
	consensusCfg.Automine = true
	cfg := &config.Config{
		Network:   0x99,
		Consensus: consensusCfg,
		GenesisConf: &config.GenesisConf{
			// Enough to stake a contract deploy.
			Alloc: map[common.Address]config.GenesisAllocation{
				addr: {Balance: new(big.Int).Mul(big.NewInt(100000), common.DnaBase)},
			},
			GodAddress:        addr,
			FirstCeremonyTime: 4070908800, //01.01.2099
		},
		Validation: &config.ValidationConfig{},
		Blockchain: &config.BlockchainConfig{},
	}
	source, sourceAppState := blockchain.NewCustomTestBlockchainWithConfig(0, 0, key, cfg)
	t.Cleanup(source.SecStore().Destroy)
	syncing, appState := source.Copy()
	subManager, err := subscriptions.NewManager(t.TempDir())
	require.NoError(t, err)
	st := &fastSyncTest{source: source, sourceAppState: sourceAppState}
	logger := log.New()
	logger.SetHandler(log.FuncHandler(func(r *log.Record) error {
		st.logs = append(st.logs, r)
		return nil
	}))
	st.fs = &fastSync{
		log:               logger,
		chain:             syncing.Blockchain,
		ipfs:              syncing.Ipfs(),
		appState:          appState,
		coinBase:          addr,
		keyStore:          keystore.NewKeyStore(t.TempDir(), keystore.LightScryptN, keystore.LightScryptP),
		subManager:        subManager,
		upgrader:          upgrade.NewUpgrader(syncing.Config(), appState, db.NewMemDB()),
		pm:                &IdenaGossipHandler{connManager: &ConnManager{bannedPeers: mapset.NewSet()}, peers: newPeerSet()},
		pubKeyToAddrCache: map[string]common.Address{},
	}
	from, err := st.fs.preConsuming(syncing.Head)
	require.NoError(t, err)
	require.Equal(t, syncing.Head.Height()+1, from)
	return st
}

// generateBlock adds a block to the source chain with that many transactions from the coinbase, so
// its bloom matches the syncing node.
func (st *fastSyncTest) generateBlock(txs int) *types.Header {
	st.source.GenerateBlocks(1, txs)
	st.headers = append(st.headers, st.source.Head)
	return st.source.Head
}

// generateContractBlock adds a block to the source chain with a contract deploy from the coinbase,
// which has a receipt. A proposer skips contract transactions after a block older than a minute,
// and the test chain starts at time 0, so a block at the current time goes first.
func (st *fastSyncTest) generateContractBlock(t *testing.T) *types.Header {
	recent := st.source.ProposeBlock([]byte{}).Block
	require.NoError(t, st.source.AddBlock(recent, nil, collector.NewStatsCollector()))
	st.headers = append(st.headers, recent.Header)

	attachment := attachments.CreateDeployContractAttachment(embedded.MultisigContract, nil, nil,
		common.ToBytes(byte(2)), common.ToBytes(byte(2)))
	payload, err := attachment.ToBytes()
	require.NoError(t, err)
	stake := blockchain.ConvertToFloat(new(big.Int).Mul(st.sourceAppState.State.FeePerGas(), big.NewInt(3000000)))
	tx := blockchain.BuildTxWithFeeEstimating(st.sourceAppState, st.fs.coinBase, nil, types.DeployContractTx, stake,
		decimal.Zero, decimal.Zero, 0, 0, payload)
	tx, err = st.source.SecStore().SignTx(tx)
	require.NoError(t, err)
	require.NoError(t, st.source.AddTx(tx))

	header := st.generateBlock(0)
	require.Len(t, st.source.GetBlock(header.Hash()).Body.Transactions, 1)
	require.NotEmpty(t, header.ProposedHeader.TxReceiptsCid)
	return header
}

// serveTransactions puts the body and the receipts of a source block in the syncing node's IPFS.
func (st *fastSyncTest) serveTransactions(t *testing.T, header *types.Header) {
	st.serveBody(t, header)
	st.serveReceipts(t, header)
}

func (st *fastSyncTest) serveBody(t *testing.T, header *types.Header) {
	st.serve(t, header.ProposedHeader.IpfsHash, st.source.GetBlock(header.Hash()).Body.ToBytes())
}

func (st *fastSyncTest) serveReceipts(t *testing.T, header *types.Header) {
	if len(header.ProposedHeader.TxReceiptsCid) == 0 {
		return
	}
	var receipts types.TxReceipts
	for _, tx := range st.source.GetBlock(header.Hash()).Body.Transactions {
		receipts = append(receipts, st.source.GetReceipt(tx.Hash()))
	}
	data, err := receipts.ToBytes()
	require.NoError(t, err)
	st.serve(t, header.ProposedHeader.TxReceiptsCid, data)
}

func (st *fastSyncTest) serve(t *testing.T, cid []byte, data []byte) {
	c, err := st.fs.ipfs.Add(data, true)
	require.NoError(t, err)
	require.Equal(t, cid, c.Bytes())
}

// invalidIpfs serves data that cannot be decoded for the given CIDs.
type invalidIpfs struct {
	ipfs.Proxy
	cids [][]byte
}

func (p *invalidIpfs) Get(key []byte, dataType ipfs.DataType) ([]byte, error) {
	for _, c := range p.cids {
		if bytes.Equal(key, c) {
			return []byte("not a block body or receipts"), nil
		}
	}
	return p.Proxy.Get(key, dataType)
}

// blocks returns the generated headers with a cert on the last one only, as fast sync gets most
// headers.
func (st *fastSyncTest) blocks() []*block {
	var blocks []*block
	for _, header := range st.headers {
		blocks = append(blocks, &block{Header: header})
	}
	last := blocks[len(blocks)-1]
	last.Cert = st.source.GetCertificate(last.Header.Hash())
	return blocks
}

// batchOf returns the blocks as one batch from a peer. No other peer is connected, so the batch
// cannot be requested again.
func (st *fastSyncTest) batchOf(blocks []*block) *batch {
	from, to := blocks[0].Header.Height(), blocks[len(blocks)-1].Header.Height()
	st.fs.manifest = &snapshot.Manifest{Height: to}
	b := &batch{from: from, to: to, p: &protoPeer{id: testServingPeer, log: log.New()}, headers: make(chan *block, len(blocks))}
	for _, block := range blocks {
		b.headers <- block
	}
	return b
}

// requireIndexed checks the local history of the block's transactions: the transaction index, the
// coinbase's address history and, if the block has receipts, the receipt index.
func (st *fastSyncTest) requireIndexed(t *testing.T, header *types.Header) {
	txs := st.source.GetBlock(header.Hash()).Body.Transactions
	require.NotEmpty(t, txs)
	for _, tx := range txs {
		idx := st.fs.chain.GetTxIndex(tx.Hash())
		require.NotNil(t, idx)
		require.Equal(t, header.Hash(), idx.BlockHash)
		saved := st.savedTx(tx.Hash())
		require.NotNil(t, saved)
		require.Equal(t, header.Hash(), saved.BlockHash)
		if len(header.ProposedHeader.TxReceiptsCid) > 0 {
			receipt := st.fs.chain.GetReceipt(tx.Hash())
			require.NotNil(t, receipt)
			require.Equal(t, tx.Hash(), receipt.TxHash)
		}
	}
}

func (st *fastSyncTest) requireNotIndexed(t *testing.T, header *types.Header) {
	txs := st.source.GetBlock(header.Hash()).Body.Transactions
	require.NotEmpty(t, txs)
	for _, tx := range txs {
		require.Nil(t, st.fs.chain.GetTxIndex(tx.Hash()))
		require.Nil(t, st.savedTx(tx.Hash()))
		require.Nil(t, st.fs.chain.GetReceipt(tx.Hash()))
	}
}

func (st *fastSyncTest) requireTransactionsWithoutReceipts(t *testing.T, header *types.Header) {
	for _, tx := range st.source.GetBlock(header.Hash()).Body.Transactions {
		require.NotNil(t, st.fs.chain.GetTxIndex(tx.Hash()))
		require.NotNil(t, st.savedTx(tx.Hash()))
		require.Nil(t, st.fs.chain.GetReceipt(tx.Hash()))
	}
}

// logged reports whether fast sync logged a record at the level for the header.
func (st *fastSyncTest) logged(lvl log.Lvl, header *types.Header) bool {
	for _, r := range st.logs {
		for i := 0; r.Lvl == lvl && i+1 < len(r.Ctx); i += 2 {
			if r.Ctx[i] == "height" && r.Ctx[i+1] == header.Height() {
				return true
			}
		}
	}
	return false
}

// savedTx returns the transaction from the coinbase's address history.
func (st *fastSyncTest) savedTx(hash common.Hash) *types.SavedTransaction {
	txs, _ := st.fs.chain.ReadTxs(st.fs.coinBase, 100, nil)
	for _, saved := range txs {
		if saved.Tx.Hash() == hash {
			return saved
		}
	}
	return nil
}

func TestFastSyncAppliesHeadersWhoseTransactionsAreMissing(t *testing.T) {
	st := newFastSyncTest(t)
	missing := st.generateBlock(1)
	served := st.generateContractBlock(t)
	last := st.generateBlock(0)
	st.serveTransactions(t, served)

	err := st.fs.processBatch(st.batchOf(st.blocks()), 1)

	// The first block's body is not in IPFS: its header is stored anyway, and so are the headers
	// after it, without requesting them again. The contract deploy, whose body and receipts are
	// served, is in the local history.
	require.NoError(t, err)
	require.Equal(t, last.Hash(), st.fs.chain.PreliminaryHead.Hash())
	for _, header := range st.headers {
		require.Equal(t, header.Hash(), st.fs.chain.GetBlockHeaderByHeight(header.Height()).Hash())
	}
	require.Zero(t, st.fs.pm.connManager.bannedPeers.Cardinality())
	require.Empty(t, st.fs.deferredHeaders)
	st.requireNotIndexed(t, missing)
	st.requireIndexed(t, served)
	require.True(t, st.logged(log.LvlWarn, missing))
	require.False(t, st.logged(log.LvlError, missing))
}

func TestFastSyncPreservesTransactionsWhenReceiptsAreMissing(t *testing.T) {
	st := newFastSyncTest(t)
	contract := st.generateContractBlock(t)
	st.generateBlock(0)
	st.serveBody(t, contract)

	err := st.fs.processBatch(st.batchOf(st.blocks()), 1)

	// The body is served but not the receipts: keep its transaction index and address history,
	// which also drive local effects such as deleting the node's own flip.
	require.NoError(t, err)
	st.requireTransactionsWithoutReceipts(t, contract)
	require.True(t, st.logged(log.LvlWarn, contract))
}

func TestFastSyncLogsUndecodableTransactionsAsError(t *testing.T) {
	st := newFastSyncTest(t)
	invalidBody := st.generateBlock(1)
	invalidReceipts := st.generateContractBlock(t)
	last := st.generateBlock(0)
	st.serveBody(t, invalidReceipts)
	st.fs.ipfs = &invalidIpfs{Proxy: st.fs.ipfs, cids: [][]byte{
		invalidBody.ProposedHeader.IpfsHash,
		invalidReceipts.ProposedHeader.TxReceiptsCid,
	}}

	err := st.fs.processBatch(st.batchOf(st.blocks()), 1)

	// Data that IPFS serves but that cannot be decoded points to a bug rather than to missing data:
	// it is logged as an error, and the headers are stored as when the data is missing.
	require.NoError(t, err)
	require.Equal(t, last.Hash(), st.fs.chain.PreliminaryHead.Hash())
	st.requireNotIndexed(t, invalidBody)
	st.requireTransactionsWithoutReceipts(t, invalidReceipts)
	for _, header := range []*types.Header{invalidBody, invalidReceipts} {
		require.True(t, st.logged(log.LvlError, header))
		require.False(t, st.logged(log.LvlWarn, header))
	}
}

func TestFastSyncCompletesBatchWhoseLastTransactionsAreMissing(t *testing.T) {
	st := newFastSyncTest(t)
	st.generateBlock(0)
	last := st.generateBlock(1)

	err := st.fs.processBatch(st.batchOf(st.blocks()), 1)

	// The last header of the batch is stored before its body is read: the batch is complete.
	require.NoError(t, err)
	require.Equal(t, last.Hash(), st.fs.chain.PreliminaryHead.Hash())
	require.Zero(t, st.fs.pm.connManager.bannedPeers.Cardinality())
	st.requireNotIndexed(t, last)
}

func TestFastSyncResumesAtHeaderWithInvalidIdentityDiff(t *testing.T) {
	st := newFastSyncTest(t)
	first := st.generateBlock(0)
	second := st.generateBlock(0)
	blocks := st.blocks()
	blocks[1].IdentityDiff = &state.IdentityStateDiff{Values: []*state.IdentityStateDiffValue{
		{Address: common.Address{0x1}, Value: []byte{0x1}},
	}}

	err := st.fs.processBatch(st.batchOf(blocks), 1)

	// The diff does not match the identity root of the second header: its peer is banned, the
	// header is not stored and the batch is requested again from it.
	require.EqualError(t, err, fmt.Sprintf("batch (%v-%v) can't be loaded", second.Height(), second.Height()))
	require.True(t, st.fs.pm.connManager.bannedPeers.Contains(testServingPeer))
	require.Equal(t, first.Hash(), st.fs.chain.PreliminaryHead.Hash())
}
